const lang = {
  en: {
    search: "Search",
    gptPlaceHolder: "what would you like to watch today?",
    signIn: "SignIn",
    signUP: "SignUP",
    forgetPass: "Forget Password",
    netToFlix: "New to Netflix?",
    now: "Now",
    already: "Already User?",
    fname: "Full Name",
    Email: "Email Address",
    pass: "Password",
  },
  hi: {
    search: "खोज",
    gptPlaceHolder: "आज आप क्या देखना चाहेंगे?",
    signIn: "दाखिल करना ",
    signUP: "साइन अप करें",
    forgetPass: "पासवर्ड भूल गए",
    netToFlix: "नेटफ्लिक्स पर नए हैं?",
    now: "अब",
    already: "पहले से ही एक उपयोगकर्ता?",
    fname: "पूरा नाम",
    Email: "मेल पता",
    pass: "पासवर्ड",
  },
  sp: {
    search: "Buscar",
    gptPlaceHolder: "¿Qué te gustaría ver hoy?",
    signIn: "Iniciar sesión",
    signUP: "Inscribirse",
    forgetPass: "Contraseña olvidada",
    netToFlix: "Nuevo en Netflix",
    now: "Ahora",
    already: "Ya eres usuario?",
    fname: "Nombre completo",
    Email: "Dirección de correo electrónico",
    pass: "Contraseña",
  },
  kor: {
    search: "찾다",
    gptPlaceHolder: "오늘은 무엇을 보고 싶나요?",
    signIn: "로그인",
    signUP: "가입하기",
    forgetPass: "비밀번호 분실",
    netToFlix: "넷플릭스를 처음 접하는 사람",
    now: "지금",
    already: "이미 사용자입니다?",
    fname: "성명",
    Email: "이메일 주소",
    pass: "비밀번호",
  },
  russ: {
    search: "Поиск",
    gptPlaceHolder: "что бы ты хотел посмотреть сегодня?",
    signIn: "Войти",
    signUP: "Зарегистрироваться",
    forgetPass: "Забыть пароль",
    already: "Уже пользователь?",
    netToFlix: "Новое в Netflix",
    now: "Сейчас",
    fname: "Полное имя",
    Email: "Адрес электронной почты",
    pass: "Пароль",
  },
  bhoj: {
    search: "तलाशी",
    gptPlaceHolder: "आज रउवा का देखल चाहब?",
    signIn: "साइन इन करीं",
    signUP: "साइनअप कर लीं",
    forgetPass: "पासवर्ड भूल जाइए",
    netToFlix: "नेटफ्लिक्स खातिर नया बा",
    now: "अबहिं",
    already: "पहिलहीं से एगो यूजर बा?",
    fname: "पूरा नाम बा",
    Email: "ईमेल के पता बा",
    pass: "पासवर्ड",
  },
  guj: {
    search: "શોધો",
    gptPlaceHolder: "તમે આજે શું જોવા માંગો છો?",
    signIn: "સાઇન ઇન કરો",
    signUP: "સાઇન અપ કરો",
    forgetPass: "પાસવર્ડ ભૂલી જાઓ",
    netToFlix: "Netflix માટે નવા છો?",
    now: "હવે",
    already: "પહેલેથી જ વપરાશકર્તા?",
    fname: "પૂરું નામ",
    Email: "ઈ - મેઈલ સરનામું",
    pass: "પાસવર્ડ",
  },
};
export default lang;
